version: "3.9"
services:
  postgres1:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "YAKUNYUSHKIN_206"
      POSTGRES_USER: "YAKUNYUSHKIN_206"
      POSTGRES_PASSWORD: "YAKUNYUSHKIN_206"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/db/scripts/library.sql:/docker-entrypoint-initdb.d/library.sql
      - ./docker/db/scripts/secondTask.sql:/docker-entrypoint-initdb.d/secondTask.sql
      - ./docker/db/scripts/thirdTask.sql:/docker-entrypoint-initdb.d/thirdTask.sql
      - ./dz/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"